### ISSUE TITLE
404 on Documentation

### ISSUE THREAD

**Issue by rblazquez** [gpc/jms#14]
Im trying access documentation for several days and getting a 404.

**Comment by graemerocher** [comment]
Link has changed http://gpc.github.io/jms/

**Comment by rblazquez** [comment]
Hi @graemerocher 

I know ... but in the new location when i try to access "User Guide" --> http://gpc.github.io/grails-jms/docs/manual/index.html

I get 404

**Comment by graemerocher** [comment]
http://gpc.github.io/jms/docs/manual/index.html

**Comment by rblazquez** [comment]
Thanks.
