### ISSUE TITLE
Not working in Grails 3.2

### ISSUE THREAD

**Issue by lploom** [gpc/jms#24]
This is probably because, with the release of Grails 3.2, most of the deprecated methods/classes have been removed. (https://github.com/grails/grails-core/pull/10124)
One of the removed classes is org.codehaus.groovy.grails.commons.GrailsClassUtils which now resides in grails.util.GrailsClassUtils (since 2014!!). The JMS plugin, however, is still looking in old location.

**Comment by purpleraven** [comment]
fixed in RC1
