### ISSUE TITLE
Is JMS plugin compatible with grails 3.x?

### ISSUE THREAD

**Issue by swzaidi** [gpc/jms#37]
Hi!,

Is JMS plugin compatible with grails 3.x?

Regards,
Shiraz

**Comment by demon101** [comment]
@swzaidi yes, I use it with grails 3.1 and grails 3.2

**Comment by sotcsa** [comment]
But not compatible with 3.3 (the deprecated GrailsClassUtils class removed)

So instead of 
import org.codehaus.groovy.grails.commons.GrailsClassUtils

should be

import grails.util.GrailsClassUtils
