### ISSUE TITLE
exposes dependency on org.grails.grails-dependencies

### ISSUE THREAD

**Issue by jchharris** [gpc/jms#55]
The pom file associated with the artifact exposes a runtime dependency on org.grails.grails-dependencies.  I think grails-dependencies should be treated as a BOM and not exposed as an explicit dependency for the jms plugin.

See https://repo1.maven.org/maven2/io/github/gpc/jms/4.0.0/jms-4.0.0.pom

Relates to https://github.com/grails/grails-core/issues/11753

**Comment by sbglasius** [comment]
@jchharris thank you for reporting. Did 4.0.1 solve your issue?

**Comment by jchharris** [comment]
@sbglasius Thanks for such a quick resolution.  Yes, the issue is resolved
