### ISSUE TITLE
The context startup does not take into account the setting of `auto-startup` to false.

### ISSUE THREAD

**Issue by jindalshivali** [gpc/jms#56]
Steps to reproduce:

Define a listener bean:

```
eventListenerContainer {
            concurrentConsumers = 10
            autoStartup = false
            connectionFactoryBean = "jmsConnectionFactory"
            messageSelector = null
            cacheLevel = 0
        }
```

When the application server starts, the eventListenerContainer is already running (isActive=true, and isRunning=true but autoStartup=false)

This seems to be because the plugin code calls the start() method on all the listener containers during application Context start  irrespective of whether or not the `autoStartup` field is set to true.

It looks like the code in below file
https://github.com/gpc/jms/blob/master/src/main/groovy/grails/plugin/jms/JmsGrailsPlugin.groovy
Method 

```
doWithApplicationContext():

 void doWithApplicationContext() {
        listenerConfigs.each { serviceClassName, serviceClassListenerConfigs ->
            serviceClassListenerConfigs.each {
                startListenerContainer(it, applicationContext)
            }
        }
 ```       
 
The code above starts all the containers irrespective of the autoStartup property.

**Comment by jindalshivali** [comment]
Currently, when the `startListenerContainer()` method is invoked, below is what happens.
```
    def startListenerContainer(listenerConfig, applicationContext) {
        applicationContext.getBean(listenerConfig.listenerContainerBeanName).start()
    }
```

Instead the code should be as below:
```
    def startListenerContainer(listenerConfig, applicationContext) {
        def listenerContainer = applicationContext.getBean(listenerConfig.listenerContainerBeanName);

        if (listenerContainer.isAutoStartup()) {
            listenerContainer.start();
        }
    }
```

**Comment by codeconsole** [comment]
@jindalshivali  can you submit a pull request?

**Comment by jindalshivali** [comment]
Added the PR to the issue.

**Comment by codeconsole** [comment]
https://github.com/gpc/jms/pull/57
